apiVersion: v1
kind: Service
metadata:
  name: vote-back-service
spec:
  ports:
  - port: 6379
  selector:
    app: vote-back
---
apiVersion: v1
kind: Service
metadata:
  name: vote-front-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: vote-front