apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vote-back-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-vote-back
    spec:
      containers:
      - name: vote-back
        image: library/redis
        ports:
        - containerPort: 6379
          name: redis

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vote-front-deployment
spec:
  replicas: {{ .Values.frontendReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-vote-front
    spec:
      containers:
      - name: vote-front
        image: microsoft/azure-vote-front:redis-v2
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REDIS
          value: {{ .Release.Name }}-vote-back-service