apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vote-back-service
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: {{ .Release.Name }}-vote-back
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vote-front-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: {{ .Release.Name }}-vote-front