apiVersion: v1
kind: Service
metadata:
  name: wordpress-test
  labels:
    app: wordpress-test
spec:
  ports:
    - port: 80
  selector:
    app: wordpress-test
    tier: frontend-test
  type: LoadBalancer

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wordpress-test
  labels:
    app: wordpress-test
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-test
        tier: frontend-test
    spec:
      containers:
      - image: <initialsYYYYMMDD>.azurecr.io/wordpress:4.8-apache
        name: wordpress-test
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql-test
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass-test
              key: password
        ports:
        - containerPort: 80
          name: wordpress-test
      imagePullSecrets:
      - name: acrsecret